name: Test Project
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Get code
        uses: ./.github/actions/checkout@v3
      - name: Install nodejs
        uses: ./.github/actions/setup-node@v3
        with:
          node-version: 17
      - name: install dependencies
        uses: npm ci
      - name: run test
        run: npm test