name: Test Project
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
